services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Model\HistoricalTimeline:
        shared: false

    assets.timeline.3y_bonds:
        class: 'App\Model\HistoricalTimeline\BondsHistoricalTimeline'
        arguments:
            $durationYears: 3

    assets.usd_rub:
        class: 'App\Service\InvestingAsset'
        arguments:
            $type: !php/const \App\Enum\AssetTypeEnum::USD_RUB
            $historicalTimeline: '@App\Model\HistoricalTimeline'
            $historicalCalculator: '@App\Service\HistoricalCalculator'
            $fileParser: '@App\Service\FileParser\FileParserUsdRub'

    assets.moex:
        class: 'App\Service\InvestingAsset'
        arguments:
            $type: !php/const \App\Enum\AssetTypeEnum::MOEX
            $historicalTimeline: '@App\Model\HistoricalTimeline'
            $historicalCalculator: '@App\Service\HistoricalCalculator'
            $fileParser: '@App\Service\FileParser\FileParserMoex'

    assets.moex_div:
        class: 'App\Service\InvestingAsset'
        arguments:
            $type: !php/const \App\Enum\AssetTypeEnum::MOEX_DIV
            $historicalTimeline: '@App\Model\HistoricalTimeline'
            $historicalCalculator: '@App\Service\HistoricalCalculator'
            $fileParser: '@App\Service\FileParser\FileParserMoexDiv'

    assets.ru_3y_bonds:
        class: 'App\Service\InvestingAsset'
        arguments:
            $type: !php/const \App\Enum\AssetTypeEnum::RU_3Y_BONDS
            $historicalTimeline: '@assets.timeline.3y_bonds'
            $historicalCalculator: '@App\Service\HistoricalCalculator\BondsHistoricalCalculator'
            $fileParser: '@App\Service\FileParser\FileParserBonds'

    assets.prices:
        class: 'App\Service\InvestingAsset'
        arguments:
            $type: !php/const \App\Enum\AssetTypeEnum::PRICES
            $historicalTimeline: '@App\Model\HistoricalTimeline'
            $historicalCalculator: '@App\Service\HistoricalCalculator'
            $fileParser: '@App\Service\FileParser\FileParserSimple'

    assets.realty_msc:
        class: 'App\Service\InvestingAsset'
        arguments:
            $type: !php/const \App\Enum\AssetTypeEnum::REALTY_MSC
            $historicalTimeline: '@App\Model\HistoricalTimeline'
            $historicalCalculator: '@App\Service\HistoricalCalculator'
            $fileParser: '@App\Service\FileParser\FileParserSimple'

    App\Service\AssetsHolder:
        calls:
            - [ addAsset, ['@assets.usd_rub']]
            - [ addAsset, [ '@assets.moex' ] ]
            - [ addAsset, [ '@assets.moex_div' ] ]
            - [ addAsset, [ '@assets.ru_3y_bonds' ] ]
            - [ addAsset, [ '@assets.prices' ] ]
            - [ addAsset, [ '@assets.realty_msc' ] ]


